export const GET_CONTACTS='GET_CONTACTS';
export const ADD_CONTACTS='ADD_CONTACTS';
export const DELETE_CONTACTS='DELETE_CONTACTS';
export const GET_CNT='GET_CNT';
export const UPDATE_CONTACT='UPDATE_CONTACT';

